### ISSUE TITLE
лаб 2

### ISSUE THREAD

**Issue by lasbio** [DmitriyDmit/BD-labs-#1]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. задание 10 - неправильно, в задании нет требования сортировки, т.е. надо отобрать первых 10 членов клуба. А у вас отобраны первые 10 по алфавиту.
3. задание 11 - AS 'объект' не работает. отбираются не только члены, но и гости.

**Comment by lasbio** [comment]
1. Задание 10 - не верно, Что будет, если удалить членов с memid in (3,7,9)?
2.  Задание 14 - не верно. Отбор сделан по стоимости аренды гостем.

**Comment by lasbio** [comment]
10 - кроме членов содержит гостя.

**Comment by DmitriyDmit** [comment]
Исправил
