### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [DmitriyDmit/BD-labs-#2]
1. Отсутствуют комментарии.
2 . Задание 2 - не точно. Использование LIKE для timestamp.
3. Задание 5 - не верно. Что будет если добавить коры 3 и 4?
4. Задание 6 - не точно. Зачем CASE в WHERE?
5.  Задание 7 - не верно.

**Comment by DmitriyDmit** [comment]
Исправил Лабу 2 и Лабу 3

**Comment by lasbio** [comment]
2 - не исправлена.
5 - в задании нет условий "теннисный",  зато есть условие на номера кортов.
7 - не верно. Должен  быть перечень  член клуба, рекомендатель.

**Comment by DmitriyDmit** [comment]
исправил

**Comment by lasbio** [comment]
7 - не верно. Ваш скрипт возвращает 22 записи, в то время как в клубе зарегистрировано 30 членов.

**Comment by DmitriyDmit** [comment]
Добрый день, мне необходимо сдать 4 лабораторную работу очно до 21 ноября, однако я заболел и не смог присутствовать на паре, я могу сдать вам ее на следующей неделе ? Если нет, то я могу полностью расписать всю информацию по коду.
